INSERT INTO EMPLOYEE(NAME, SALARY, CREATED_DATE) VALUES ('art', 10, CURRENT_TIMESTAMP) ON CONFLICT (NAME) DO NOTHING;
INSERT INTO EMPLOYEE(NAME, SALARY, CREATED_DATE) VALUES ('avi', 20, CURRENT_TIMESTAMP) ON CONFLICT (NAME) DO NOTHING;
INSERT INTO EMPLOYEE(NAME, SALARY, CREATED_DATE) VALUES ('state', 30, CURRENT_TIMESTAMP) ON CONFLICT (NAME) DO NOTHING;